package com.mlue.app.viewmodel

/**
 * A single detected behavioral pattern — used to enrich and prioritize the insights feed.
 *
 * Tone contract (Sprint 3A):
 *  ✓ Observational and gentle: "Sundays tend to slip by a little more."
 *  ✗ Diagnostic or judgmental: "You are failing on Sundays."
 *  ✗ Algorithmic or creepy: "Detected behavioral anomaly on weekday 7."
 *
 * Sprint 3A: Smart Pattern Detection
 */
data class BehavioralPattern(
    /**
     * Calm, human-toned observation ready for display in the insights feed.
     * Written as if noticed by a thoughtful companion, not generated by a system.
     */
    val message: String,

    /**
     * Priority order: 1 = highest (shown first in prioritized feed), 5 = lowest.
     * Priority 1: meaningful momentum or recovery observations
     * Priority 2: weekday patterns and trend shifts
     * Priority 3: habit-load and quiet-habit observations
     */
    val priority: Int
)
